plugins: [jekyll-paginate]

permalink: /:categories/:title/

highlighter: rouge
markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter: rouge


paginate: 5
paginate_path: "page/:num"
baseurl: ""

excerpt_separator:  '<!-- more -->'


defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      styles : [highlight.css,gitment.css,post.css]
      scripts : [gitment.js, post.js]



title: "Whernog's bb空间"
email: goldenmeilisss@gmail.com
description: ""
github:
  username: Whernog
swiftype:
  searchId: iXZyPokVfxFaBTvi64Y6
gitment:
    repo: Whernog.github.io
    client_id: 612bc7dc9bab7d00ea29
    client_secret: 9636459e0c80a54de5495e90cfb1c63831e27763

url: "https://Whernog.github.io"
imgrepo: "https://Whernog.github.io/static/img"


#url: "http://127.0.0.1:4000"
#imgrepo: "http://127.0.0.1:4000/static/img"

post_asset_folder: true
marked:
  prependRoot: true
  postAsset: true